name: sajomainventory
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  pdf: ^3.10.4
  path_provider: ^2.0.14
  flutter_email_sender: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  printing: ^5.14.2
  shared_preferences: ^2.0.12
  crypto: ^3.0.2
  google_fonts: ^6.0.0
  sqflite_common_ffi: ^2.3.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.13.0
  firebase_core: ^2.25.4  # Use the latest version
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/