import 'package:hive/hive.dart';

part 'item.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1)
class Item extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  String defaultUnit;

  Item({required this.name, required this.defaultUnit});
}
